- name: Add group "codeuser"
  group:
    name: codeuser
    gid: 2010
    state: present
  become: yes

- name: Add user "codeuser"
  user:
    name: codeuser
    comment: "User for Code Server"
    uid: 2001
    group: codeuser
    append: yes
    shell: /usr/bin/fish
  become: yes

- name: Create codeserver folder
  file:
    path: /opt/codeserver
    state: directory
  become: yes

- name: Unarchive codeserver
  unarchive:
    src: "{{ codeserver_url }}"
    dest: /opt
    remote_src: yes
    list_files: yes
    owner: codeuser
    group: codeuser
  become: yes

- name: Add codeserver service
  template:
    src: codeserver.service.j2
    dest: /etc/systemd/system/codeserver.service
  become: yes

- name: Start Codeserver service
  shell: systemctl restart codeserver
  become: yes

- name: Codeserver at startup
  shell: systemctl enable codeserver
  become: yes
